In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from skimage import color
from skimage.feature import hog
from sklearn import svm
from sklearn.metrics import classification_report,accuracy_score
from skimage.io import imread, imshow
from skimage.transform import resize
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split

In [ ]:
## Annotated Data to be downloaded from https://vision.cs.uiuc.edu/attributes/  

!tar -xvzf /content/attribute_data.tar.gz

attribute_data/
attribute_data/ayahoo_test.txt
attribute_data/README
attribute_data/attribute_names.txt
attribute_data/apascal_test.txt
attribute_data/read_att_data.m
attribute_data/apascal_train.txt
attribute_data/class_names.txt
attribute_data/display_images.m


In [ ]:
## Download images
!wget -c http://vision.cs.uiuc.edu/attributes/ayahoo_test_images.tar.gz
!tar -xvzf /content/ayahoo_test_images.tar.gz
# !wget -c http://pascallin.ecs.soton.ac.uk/challenges/VOC/voc2008/

In [ ]:
data = pd.read_csv('/content/annotated_yahoo.csv')

with open('/content/attribute_names.txt', 'r') as content: ## This is the 33 attribute names present in the affordanceKB paper
    lab = content.read()

top_33_attr = [line for line in lab.split('\n') if len(line) > 0]

data = data.rename(columns={'2D Boxy': 'Boxy_2D', '3D Boxy': 'Boxy_3D', 
                               'Vert Cyl': 'Vert_Cyl',
                               'Horiz Cyl':'Horiz_Cyl', 'Furn. Leg': 'Furn_Leg',
                               'Furn. Back': 'Furn_Back',
                               'Furn. Seat': 'Furn_Seat', 'Furn. Arm': 'Furn_Arm'})

data = data[['image'] + top_33_attr]
data.head()

image  Boxy_2D  Boxy_3D  Round  Vert_Cyl  Horiz_Cyl  Tail  Head  \
0    donkey_1.jpg        0        0      0         0          0     0     1   
1    donkey_1.jpg        0        0      0         0          0     0     1   
2  donkey_100.jpg        0        0      0         0          0     0     0   
3  donkey_102.jpg        0        0      0         0          0     1     1   
4  donkey_111.jpg        0        0      0         0          0     0     1   

   Wheel  Pedal  ...  Wood  Cloth  Furry  Glass  Feather  Wool  Clear  Shiny  \
0      0      0  ...     0      0      1      0        0     0      0      0   
1      0      0  ...     0      0      1      0        0     0      0      0   
2      0      0  ...     0      0      0      0        0     0      0      0   
3      0      0  ...     0      0      1      0        0     0      0      0   
4      0      0  ...     0      0      1      0        0     0      0      0   

   Vegetation  Leather  
0           0        0  
1           0        0  
2           0        0  
3           0        0  
4           0        0  

[5 rows x 34 columns]

In [ ]:
import keras, tensorflow
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
# from keras.utils import load_img
from tensorflow.keras.utils import load_img, img_to_array
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tqdm import tqdm
%matplotlib inline

In [ ]:
train, test = train_test_split(data, random_state=42, test_size=0.1)
train = train.reset_index(drop=True)
test = test.reset_index(drop=True)
train.head()

image  Boxy_2D  Boxy_3D  Round  Vert_Cyl  Horiz_Cyl  Tail  Head  \
0       bag_599.jpg        0        0      0         0          1     0     0   
1      goat_212.jpg        0        0      0         0          0     1     1   
2  building_819.jpg        0        1      0         0          0     0     0   
3     jetski_10.jpg        0        1      0         0          0     0     0   
4       bag_332.jpg        0        1      0         1          0     0     0   

   Wheel  Pedal  ...  Wood  Cloth  Furry  Glass  Feather  Wool  Clear  Shiny  \
0      0      0  ...     0      0      0      0        0     0      0      0   
1      0      0  ...     0      0      1      0        0     0      0      0   
2      0      0  ...     1      0      0      1        0     0      0      0   
3      0      0  ...     0      0      0      0        0     0      0      0   
4      0      0  ...     0      0      0      0        0     0      0      1   

   Vegetation  Leather  
0           0        1  
1           0        0  
2           0        0  
3           0        0  
4           0        1  

[5 rows x 34 columns]

In [ ]:
train_image = []
for i in tqdm(range(train.shape[0])):
    img = load_img('/content/ayahoo_test_images/'+train['image'][i],target_size=(200,200,3))
    img = img_to_array(img)
    img = img/255
    train_image.append(img)
X = np.array(train_image)

100%|██████████| 2379/2379 [00:16<00:00, 148.09it/s]


In [ ]:
y = np.array(train.drop(['image'],axis=1))
y.shape

(2379, 33)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.1)

In [ ]:
model = Sequential()
model.add(Conv2D(filters=16, kernel_size=(5, 5), activation="relu", input_shape=(200,200,3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(33, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_24 (Conv2D)          (None, 196, 196, 16)      1216      
                                                                 
 max_pooling2d_22 (MaxPoolin  (None, 98, 98, 16)       0         
 g2D)                                                            
                                                                 
 dropout_30 (Dropout)        (None, 98, 98, 16)        0         
                                                                 
 conv2d_25 (Conv2D)          (None, 94, 94, 32)        12832     
                                                                 
 max_pooling2d_23 (MaxPoolin  (None, 47, 47, 32)       0         
 g2D)                                                            
                                                                 
 dropout_31 (Dropout)        (None, 47, 47, 32)       

In [ ]:

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:

model.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test), batch_size=32)

Epoch 1/20
67/67 [==============================] - 161s 2s/step - loss: 0.4464 - accuracy: 0.0929 - val_loss: 0.3239 - val_accuracy: 0.1891
Epoch 2/20
67/67 [==============================] - 153s 2s/step - loss: 0.3065 - accuracy: 0.1182 - val_loss: 0.2615 - val_accuracy: 0.1849
Epoch 3/20
67/67 [==============================] - 158s 2s/step - loss: 0.2743 - accuracy: 0.1425 - val_loss: 0.2507 - val_accuracy: 0.1849
Epoch 4/20
67/67 [==============================] - 154s 2s/step - loss: 0.2608 - accuracy: 0.1728 - val_loss: 0.2402 - val_accuracy: 0.2101
Epoch 5/20
67/67 [==============================] - 152s 2s/step - loss: 0.2486 - accuracy: 0.1681 - val_loss: 0.2322 - val_accuracy: 0.2689
Epoch 6/20
67/67 [==============================] - 151s 2s/step - loss: 0.2416 - accuracy: 0.1966 - val_loss: 0.2258 - val_accuracy: 0.2563
Epoch 7/20
67/67 [==============================] - 152s 2s/step - loss: 0.2334 - accuracy: 0.2055 - val_loss: 0.2222 - val_accuracy: 0.2773
Epoch 8/20
67

## Predicting visual attributes for the noun phrases extracted earlier

In [ ]:
noun_phrases_images = pd.read_csv('/content/images.csv')

noun_phrases_images.head()

Unnamed: 0                   noun  \
0           0  Product and geography   
1           1  Product and geography   
2           2  Product and geography   
3           3  Product and geography   
4           4  Product and geography   

                                                 img   img_id  
0  https://cs.stanford.edu/people/rak248/VG_100K/...   713545  
1  https://cs.stanford.edu/people/rak248/VG_100K/...  1159702  
2  https://cs.stanford.edu/people/rak248/VG_100K/...  2320213  
3  https://cs.stanford.edu/people/rak248/VG_100K/...  2321812  
4  https://cs.stanford.edu/people/rak248/VG_100K_...  2417008

In [ ]:
noun_phrase_to_image_mapping = {} # add multiple images for each np 
for id, rows in noun_phrases_images.iterrows():
    nps = rows[1]
    img_link = rows[2]  
    if nps in noun_phrase_to_image_mapping.keys():
        noun_phrase_to_image_mapping[nps].append(img_link)
    else:
        noun_phrase_to_image_mapping[nps] = [img_link]

In [ ]:
from io import BytesIO
import urllib




def loadImage(URL):
    with urllib.request.urlopen(URL) as url:
        img = load_img(BytesIO(url.read()), target_size=(200,200,3))
        img = img_to_array(img)
        img = img/255
    return img


threshold = 0.4
im = noun_phrase_to_image_mapping['Product and geography']

pred_image = []
for i in tqdm(range(len(im))):
    print(im[i])
    img = loadImage(im[i])
    pred_image.append(img)
X_pred = np.array(pred_image)


classes = np.array(train.columns[2:])
# proba = model.predict(img.reshape(1,128,128,3))


proba = model.predict(X_pred)
proba = np.array([[0 if a_ < threshold else 1 for a_ in a] for a in proba])
top_3 = np.argsort(proba[0])

print(proba)
# top_3
# X_test.shape

  0%|          | 0/5 [00:00<?, ?it/s]

https://cs.stanford.edu/people/rak248/VG_100K/713545.jpg


 20%|██        | 1/5 [00:00<00:02,  1.41it/s]

https://cs.stanford.edu/people/rak248/VG_100K/1159702.jpg


 40%|████      | 2/5 [00:01<00:02,  1.45it/s]

https://cs.stanford.edu/people/rak248/VG_100K/2320213.jpg


 60%|██████    | 3/5 [00:01<00:01,  1.64it/s]

https://cs.stanford.edu/people/rak248/VG_100K/2321812.jpg


 80%|████████  | 4/5 [00:02<00:00,  1.75it/s]

https://cs.stanford.edu/people/rak248/VG_100K_2/2417008.jpg


100%|██████████| 5/5 [00:02<00:00,  1.70it/s]


1/1 [==============================] - 0s 225ms/step
[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
classes = np.array(train.columns[1:])
classes

array(['Boxy_2D', 'Boxy_3D', 'Round', 'Vert_Cyl', 'Horiz_Cyl', 'Tail',
       'Head', 'Wheel', 'Pedal', 'Handlebars', 'Text', 'Label',
       'Furn_Leg', 'Furn_Back', 'Furn_Seat', 'Furn_Arm', 'Rein', 'Saddle',
       'Pot', 'Screen', 'Skin', 'Metal', 'Plastic', 'Wood', 'Cloth',
       'Furry', 'Glass', 'Feather', 'Wool', 'Clear', 'Shiny',
       'Vegetation', 'Leather'], dtype=object)

In [ ]:
from tqdm import tqdm

def most_freq(lst):
    return max(set(lst), key=lst.count)

df_dict = {}
df_dict['noun_phrase'] = []
final_attr_labels = {}
i = 0
for nps, links in tqdm(noun_phrase_to_image_mapping.items()):
    df_dict['noun_phrase'].append(nps)
    # final_attr_labels[nps] = {}
    pred_image = []
    for im in links:
        img = loadImage(im)
        pred_image.append(img)
    X_pred = np.array(pred_image)
    proba = model.predict(X_pred)
    proba = np.array([[0 if a_ < threshold else 1 for a_ in a] for a in proba])
    predictions = proba.sum(axis=0)
    predictions = np.array([1 if a_ > 2 else 0 for a_ in predictions])

    print(predictions)
    for category in classes:
        if category in final_attr_labels.keys():
            final_attr_labels[category].append(predictions[list(classes).index(category)])
        else:
            final_attr_labels[category] = [predictions[list(classes).index(category)]]

    
    # if i == 3:
    #     break
print(final_attr_labels)

  0%|          | 0/174 [00:00<?, ?it/s]

1/1 [==============================] - 0s 114ms/step


  1%|          | 1/174 [00:03<08:52,  3.08s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 127ms/step


  1%|          | 2/174 [00:05<08:10,  2.85s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


  2%|▏         | 3/174 [00:08<07:57,  2.79s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 193ms/step


  2%|▏         | 4/174 [00:13<10:35,  3.74s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 109ms/step


  3%|▎         | 5/174 [00:16<09:15,  3.29s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 112ms/step


  3%|▎         | 6/174 [00:18<08:41,  3.11s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


  4%|▍         | 7/174 [00:21<08:16,  2.98s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 109ms/step


  5%|▍         | 8/174 [00:24<07:58,  2.88s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


  5%|▌         | 9/174 [00:27<07:47,  2.83s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


  6%|▌         | 10/174 [00:29<07:43,  2.83s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


  6%|▋         | 11/174 [00:32<07:31,  2.77s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


  7%|▋         | 12/174 [00:35<07:24,  2.74s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


  7%|▋         | 13/174 [00:37<07:15,  2.70s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


  8%|▊         | 14/174 [00:40<07:02,  2.64s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


  9%|▊         | 15/174 [00:43<07:08,  2.70s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 118ms/step


  9%|▉         | 16/174 [00:45<07:11,  2.73s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 10%|▉         | 17/174 [00:48<06:53,  2.63s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 10%|█         | 18/174 [00:51<07:04,  2.72s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 385ms/step


 11%|█         | 19/174 [01:00<12:25,  4.81s/it]

[0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 11%|█▏        | 20/174 [01:03<10:47,  4.20s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 12%|█▏        | 21/174 [01:06<09:37,  3.78s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 13%|█▎        | 22/174 [01:09<08:38,  3.41s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 201ms/step


 13%|█▎        | 23/174 [01:11<07:56,  3.16s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 14%|█▍        | 24/174 [01:14<07:27,  2.98s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 14%|█▍        | 25/174 [01:17<07:21,  2.96s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 120ms/step


 15%|█▍        | 26/174 [01:19<07:10,  2.91s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 109ms/step


 16%|█▌        | 27/174 [01:22<06:47,  2.77s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 112ms/step


 16%|█▌        | 28/174 [01:24<06:32,  2.69s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 120ms/step


 17%|█▋        | 29/174 [01:27<06:35,  2.73s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 117ms/step


 17%|█▋        | 30/174 [01:30<06:38,  2.77s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 18%|█▊        | 31/174 [01:33<06:47,  2.85s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 18%|█▊        | 32/174 [01:36<06:46,  2.87s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 111ms/step


 19%|█▉        | 33/174 [01:39<06:39,  2.83s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 20%|█▉        | 34/174 [01:41<06:24,  2.75s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 116ms/step


 20%|██        | 35/174 [02:40<45:19, 19.56s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 117ms/step


 21%|██        | 36/174 [02:43<33:18, 14.48s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 111ms/step


 21%|██▏       | 37/174 [02:45<24:56, 10.92s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 132ms/step


 22%|██▏       | 38/174 [02:48<19:08,  8.44s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 22%|██▏       | 39/174 [02:51<15:09,  6.74s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 130ms/step


 23%|██▎       | 40/174 [02:53<12:09,  5.45s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 117ms/step


 24%|██▎       | 41/174 [02:56<10:11,  4.60s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 111ms/step


 24%|██▍       | 42/174 [02:59<09:02,  4.11s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 25%|██▍       | 43/174 [03:01<08:03,  3.69s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 126ms/step


 25%|██▌       | 44/174 [03:04<07:17,  3.37s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 112ms/step


 26%|██▌       | 45/174 [03:07<06:40,  3.11s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 127ms/step


 26%|██▋       | 46/174 [03:09<06:26,  3.02s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 27%|██▋       | 47/174 [03:12<06:18,  2.98s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 109ms/step


 28%|██▊       | 48/174 [03:15<05:59,  2.85s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 120ms/step


 28%|██▊       | 49/174 [03:18<05:51,  2.81s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 125ms/step


 29%|██▊       | 50/174 [03:20<05:39,  2.74s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 206ms/step


 29%|██▉       | 51/174 [03:23<05:36,  2.74s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 30%|██▉       | 52/174 [03:26<05:33,  2.74s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 30%|███       | 53/174 [03:28<05:27,  2.71s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 31%|███       | 54/174 [03:31<05:19,  2.66s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 105ms/step


 32%|███▏      | 55/174 [03:33<05:11,  2.61s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 197ms/step


 32%|███▏      | 56/174 [03:39<06:41,  3.40s/it]

[0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 122ms/step


 33%|███▎      | 57/174 [03:41<06:06,  3.13s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 33%|███▎      | 58/174 [03:44<05:42,  2.95s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 121ms/step


 34%|███▍      | 59/174 [03:46<05:25,  2.83s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 158ms/step


 34%|███▍      | 60/174 [03:49<05:17,  2.78s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 193ms/step


 35%|███▌      | 61/174 [03:54<06:38,  3.53s/it]

[0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 36%|███▌      | 62/174 [03:57<06:04,  3.26s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 191ms/step


 36%|███▌      | 63/174 [04:02<06:58,  3.77s/it]

[0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 107ms/step


 37%|███▋      | 64/174 [04:04<06:10,  3.37s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 119ms/step


 37%|███▋      | 65/174 [04:07<05:37,  3.10s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 109ms/step


 38%|███▊      | 66/174 [04:09<05:18,  2.95s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 116ms/step


 39%|███▊      | 67/174 [04:12<05:09,  2.90s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 39%|███▉      | 68/174 [04:14<04:56,  2.80s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 205ms/step


 40%|███▉      | 69/174 [04:20<06:12,  3.55s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 40%|████      | 70/174 [04:23<05:45,  3.32s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 116ms/step


 41%|████      | 71/174 [04:25<05:28,  3.19s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 128ms/step


 41%|████▏     | 72/174 [04:28<05:03,  2.97s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 42%|████▏     | 73/174 [04:31<04:49,  2.86s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 43%|████▎     | 74/174 [04:33<04:47,  2.87s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 111ms/step


 43%|████▎     | 75/174 [04:36<04:34,  2.77s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 44%|████▎     | 76/174 [04:39<04:32,  2.78s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 44%|████▍     | 77/174 [04:42<04:29,  2.78s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 45%|████▍     | 78/174 [04:44<04:20,  2.72s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 45%|████▌     | 79/174 [04:47<04:17,  2.71s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 117ms/step


 46%|████▌     | 80/174 [04:49<04:14,  2.71s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 112ms/step


 47%|████▋     | 81/174 [04:52<04:13,  2.73s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 47%|████▋     | 82/174 [04:55<04:09,  2.71s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 48%|████▊     | 83/174 [04:58<04:09,  2.74s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 121ms/step


 48%|████▊     | 84/174 [05:00<04:05,  2.73s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 49%|████▉     | 85/174 [05:03<04:07,  2.78s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 49%|████▉     | 86/174 [05:06<04:02,  2.75s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 50%|█████     | 87/174 [05:09<03:58,  2.74s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 111ms/step


 51%|█████     | 88/174 [05:11<03:54,  2.73s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 51%|█████     | 89/174 [05:14<03:53,  2.75s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 123ms/step


 52%|█████▏    | 90/174 [05:17<03:44,  2.67s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 52%|█████▏    | 91/174 [05:20<03:45,  2.71s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 53%|█████▎    | 92/174 [05:22<03:38,  2.67s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 119ms/step


 53%|█████▎    | 93/174 [05:25<03:38,  2.70s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 119ms/step


 54%|█████▍    | 94/174 [05:27<03:30,  2.63s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 119ms/step


 55%|█████▍    | 95/174 [05:30<03:31,  2.68s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 123ms/step


 55%|█████▌    | 96/174 [05:33<03:33,  2.73s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 203ms/step


 56%|█████▌    | 97/174 [05:36<03:29,  2.72s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 56%|█████▋    | 98/174 [05:39<03:28,  2.74s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 105ms/step


 57%|█████▋    | 99/174 [05:41<03:31,  2.81s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 57%|█████▋    | 100/174 [05:44<03:26,  2.79s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 58%|█████▊    | 101/174 [05:47<03:22,  2.78s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 59%|█████▊    | 102/174 [05:50<03:16,  2.73s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 206ms/step


 59%|█████▉    | 103/174 [05:55<04:12,  3.56s/it]

[0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 60%|█████▉    | 104/174 [05:58<03:52,  3.33s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 60%|██████    | 105/174 [06:00<03:34,  3.11s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 61%|██████    | 106/174 [06:03<03:19,  2.93s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 61%|██████▏   | 107/174 [06:06<03:08,  2.82s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 62%|██████▏   | 108/174 [06:08<03:04,  2.80s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 117ms/step


 63%|██████▎   | 109/174 [06:11<02:59,  2.77s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 112ms/step


 63%|██████▎   | 110/174 [06:14<02:56,  2.75s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 64%|██████▍   | 111/174 [06:16<02:54,  2.76s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 105ms/step


 64%|██████▍   | 112/174 [06:19<02:47,  2.70s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 65%|██████▍   | 113/174 [06:22<02:43,  2.69s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 66%|██████▌   | 114/174 [06:24<02:39,  2.66s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 196ms/step


 66%|██████▌   | 115/174 [06:29<03:21,  3.42s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 67%|██████▋   | 116/174 [06:32<03:05,  3.20s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 112ms/step


 67%|██████▋   | 117/174 [06:35<02:51,  3.00s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 68%|██████▊   | 118/174 [06:37<02:43,  2.93s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 68%|██████▊   | 119/174 [06:40<02:39,  2.91s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 69%|██████▉   | 120/174 [06:43<02:34,  2.86s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 70%|██████▉   | 121/174 [06:46<02:32,  2.87s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 70%|███████   | 122/174 [06:49<02:27,  2.84s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 130ms/step


 71%|███████   | 123/174 [06:51<02:22,  2.80s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 111ms/step


 71%|███████▏  | 124/174 [06:54<02:18,  2.77s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 107ms/step


 72%|███████▏  | 125/174 [06:57<02:15,  2.76s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 109ms/step


 72%|███████▏  | 126/174 [07:00<02:12,  2.76s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 111ms/step


 73%|███████▎  | 127/174 [07:02<02:07,  2.71s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 105ms/step


 74%|███████▎  | 128/174 [07:05<02:02,  2.67s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 109ms/step


 74%|███████▍  | 129/174 [07:08<02:01,  2.69s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 75%|███████▍  | 130/174 [07:10<01:57,  2.67s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 75%|███████▌  | 131/174 [07:13<01:56,  2.72s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 107ms/step


 76%|███████▌  | 132/174 [07:15<01:51,  2.65s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 107ms/step


 76%|███████▋  | 133/174 [07:18<01:49,  2.67s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 122ms/step


 77%|███████▋  | 134/174 [07:21<01:47,  2.68s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 78%|███████▊  | 135/174 [07:24<01:44,  2.68s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 109ms/step


 78%|███████▊  | 136/174 [07:26<01:42,  2.70s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 79%|███████▊  | 137/174 [07:29<01:38,  2.67s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 79%|███████▉  | 138/174 [07:32<01:39,  2.75s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 116ms/step


 80%|███████▉  | 139/174 [07:35<01:36,  2.76s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 112ms/step


 80%|████████  | 140/174 [07:37<01:33,  2.74s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 110ms/step


 81%|████████  | 141/174 [07:40<01:28,  2.70s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 107ms/step


 82%|████████▏ | 142/174 [07:43<01:28,  2.76s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 128ms/step


 82%|████████▏ | 143/174 [07:46<01:24,  2.73s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 131ms/step


 83%|████████▎ | 144/174 [07:48<01:22,  2.76s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 83%|████████▎ | 145/174 [07:51<01:17,  2.68s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 84%|████████▍ | 146/174 [07:54<01:16,  2.73s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 117ms/step


 84%|████████▍ | 147/174 [07:56<01:13,  2.72s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
1/1 [==============================] - 0s 106ms/step


 85%|████████▌ | 148/174 [07:59<01:10,  2.73s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 105ms/step


 86%|████████▌ | 149/174 [08:02<01:08,  2.73s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 109ms/step


 86%|████████▌ | 150/174 [08:04<01:04,  2.68s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 87%|████████▋ | 151/174 [08:07<01:01,  2.68s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 118ms/step


 87%|████████▋ | 152/174 [08:10<00:58,  2.66s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 88%|████████▊ | 153/174 [08:13<00:56,  2.70s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 89%|████████▊ | 154/174 [08:15<00:53,  2.69s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 201ms/step


 89%|████████▉ | 155/174 [08:21<01:06,  3.49s/it]

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 118ms/step


 90%|████████▉ | 156/174 [08:23<00:58,  3.25s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 90%|█████████ | 157/174 [08:26<00:51,  3.05s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 91%|█████████ | 158/174 [08:29<00:47,  2.97s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 117ms/step


 91%|█████████▏| 159/174 [08:31<00:42,  2.81s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 105ms/step


 92%|█████████▏| 160/174 [08:34<00:39,  2.80s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 112ms/step


 93%|█████████▎| 161/174 [08:36<00:35,  2.76s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 122ms/step


 93%|█████████▎| 162/174 [08:39<00:33,  2.81s/it]

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 94%|█████████▎| 163/174 [08:42<00:30,  2.76s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 112ms/step


 94%|█████████▍| 164/174 [08:45<00:26,  2.69s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 116ms/step


 95%|█████████▍| 165/174 [08:47<00:24,  2.68s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 114ms/step


 95%|█████████▌| 166/174 [08:50<00:21,  2.68s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 115ms/step


 96%|█████████▌| 167/174 [08:53<00:18,  2.69s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 108ms/step


 97%|█████████▋| 168/174 [08:55<00:16,  2.68s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 128ms/step


 97%|█████████▋| 169/174 [08:58<00:13,  2.68s/it]

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 129ms/step


 98%|█████████▊| 170/174 [09:01<00:10,  2.67s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 122ms/step


 98%|█████████▊| 171/174 [09:03<00:08,  2.70s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 113ms/step


 99%|█████████▉| 172/174 [09:06<00:05,  2.74s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 106ms/step


 99%|█████████▉| 173/174 [09:09<00:02,  2.74s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1/1 [==============================] - 0s 116ms/step


100%|██████████| 174/174 [09:12<00:00,  3.17s/it]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
{'Boxy_2D': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Boxy_3D': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
for lab in top_33_attr:
    df_dict[lab] = final_attr_labels[lab]

df = pd.DataFrame(df_dict)

df.head(20)

noun_phrase  Boxy_2D  Boxy_3D  Round  Vert_Cyl  Horiz_Cyl  Tail  \
0   Product and geography        0        0      0         0          0     0   
1                   cream        0        0      0         0          0     0   
2                    work        0        0      0         0          0     0   
3                     You        0        0      0         0          0     1   
4              the things        0        0      0         0          0     1   
5     the following level        0        0      0         0          0     0   
6              the people        0        0      0         0          0     0   
7     A member of my team        0        0      0         0          0     0   
8                A member        0        0      0         0          0     0   
9                 my team        0        0      0         0          0     0   
10            your orders        0        1      0         0          0     0   
11      immense precision        0        0      0         0          0     0   
12       This information        0        0      0         0          0     0   
13                   them        0        0      0         0          0     0   
14       The tennis shoes        0        0      0         0          0     0   
15      a range of prices        0        0      0         0          0     0   
16                a range        0        0      0         0          0     0   
17                 prices        0        0      0         0          0     0   
18                      I        0        1      0         0          0     1   
19             my walkman        0        0      0         0          0     0   

    Head  Wheel  Pedal  ...  Wood  Cloth  Furry  Glass  Feather  Wool  Clear  \
0      1      0      0  ...     0      0      0      0        0     0      0   
1      1      0      0  ...     0      0      1      0        0     0      0   
2      0      0      0  ...     0      0      0      0        0     0      0   
3      1      0      0  ...     0      0      1      0        0     0      0   
4      1      0      0  ...     0      0      1      0        0     0      0   
5      1      0      0  ...     0      0      1      0        0     0      0   
6      1      0      0  ...     0      0      0      0        0     0      0   
7      0      0      0  ...     0      0      0      0        0     0      0   
8      1      0      0  ...     0      0      0      0        0     0      0   
9      1      0      0  ...     0      0      0      0        0     0      0   
10     0      0      0  ...     0      0      0      0        0     0      0   
11     1      0      0  ...     0      0      1      0        0     0      0   
12     1      0      0  ...     0      0      0      0        0     0      0   
13     1      0      0  ...     0      0      0      0        0     0      0   
14     1      0      0  ...     0      0      1      0        0     0      0   
15     0      0      0  ...     0      0      0      0        0     0      0   
16     1      0      0  ...     0      0      1      0        0     0      0   
17     0      0      0  ...     0      0      0      0        0     0      0   
18     1      0      0  ...     0      0      1      0        0     0      0   
19     1      0      0  ...     0      0      0      0        0     0      0   

    Shiny  Vegetation  Leather  
0       0           0        0  
1       0           0        0  
2       0           0        0  
3       0           0        0  
4       0           0        0  
5       0           0        0  
6       0           0        0  
7       0           0        0  
8       0           0        0  
9       0           0        0  
10      0           0        0  
11      0           0        0  
12      0           0        0  
13      0           0        0  
14      0           0        0  
15      0           0        0  
16      0           0        0  
17      0           0        0  
18  

In [ ]:
df.to_csv("visual_attribute_predictions.csv")

In [ ]:
with open("/content/relation_mln.txt", 'r') as content: 
    mln_rules = content.readlines()[11:]




In [ ]:
def replace_all(text, dic):
    for i, j in dic.items():
        text = text.replace(i, j)
    return text

replace_dict = {'boxy 2d': 'boxy_2d', 'boxy 3d': 'boxy_3d', 
                               'vertical cylindrical': 'vert_cyl',
                               'vertical cylindrical':'horiz_cyl', 
                               'furniture leg': 'furn_leg',
                               'furniture Back': 'furn_back',
                               'furniture Seat': 'furn_seat', 
                               'furniture Arm': 'furn_arm'}

# replace_all(mln_rules, replace_dict)

mln_rules = [x.strip('\n') for x in mln_rules]
mln_rules = [replace_all(x, replace_dict) for x in mln_rules]
mln_scores = [x.split()[0] for x in mln_rules]
mln_attr = [x.split()[1] for x in mln_rules]
mln_affordance = [x.split()[-1] for x in mln_rules]

print(mln_scores[0], mln_attr[0], mln_affordance[0])

-0.0717154 boxy_2d grasp


In [ ]:
objects = 'The tennis shoes'
# objects = 'my team'
# objects = 'that on television'


selected_df = df.loc[df['noun_phrase']==objects]

for category in top_33_attr:
    if selected_df[category].values[0] == 1:
        if category.lower() in mln_attr:
            indexes = mln_attr.index(category.lower())
            print(category, mln_affordance[indexes], mln_scores[indexes])

# selected_df['Boxy_2D'].values[0]


Head grasp -0.023025
Furry grasp -0.0907226
